#!/bin/bash
# create a network for containers to communicate
docker network create loja-primus-net

# launch mysql 5.7 container
docker run -ti --name loja-primus-dbsrv --network loja-primus-net -e MYSQL_ROOT_PASSWORD=lojaprimus -p 3307:3306 -d mysql:5.7

# launch prestashop container
docker run -ti --name loja-primus --network loja-primus-net -e DB_SERVER=loja-primus-dbsrv -p 8080:80 -d prestashop/prestashop:latest

